Ticket9616
N-Viet-ruby-dev/question-answer pull request #3
Opened 2019-03-27 11:56 UTC by manh11117

2019-03-28 04:51 UTC, luongvietdung commented on db/seeds.rb
> +<<<<<<< HEAD
Chưa fix hết conflict. Xoá dòng này đi

2019-03-28 08:27 UTC, ducnhat1989 commented on Gemfile
> +gem "rubocop"
để trong development

2019-03-28 10:24 UTC, N-Viet-ruby-dev requested changes

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Bundler/OrderedGems:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Layout/EmptyLines:
remove

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/ExpandPathArguments:
remove

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/FrozenStringLiteralComment:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/SymbolArray:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Rails/UnknownEnv:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +AllCops:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/StringLiterals:
move to .rubocop.yml

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/StderrPuts:
remove

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/RedundantBegin:
remove

2019-03-28 10:24 UTC, N-Viet-ruby-dev commented on .rubocop_todo.yml
> +Style/MixinUsage:
remove

2019-03-28 10:27 UTC, luongvietdung commented on .rubocop.yml
> +  Max: 130
change to `120`

2019-03-28 10:28 UTC, luongvietdung commented on .rubocop.yml
> +Style/FrozenStringLiteralComment:
Xoá từ dòng này đến cuối file

2019-03-28 10:29 UTC, luongvietdung commented on .rubocop_todo.yml
> +    - 'db/*.rb'
change 'db/*.rb'  to db/schema.rb

2019-03-28 11:27 UTC, luongvietdung commented on .rubocop.yml
> +  Max: 1500
change to `200`

2019-03-29 01:39 UTC, N-Viet-ruby-dev commented on .rubocop.yml
> +Rails/HasAndBelongsToMany:
remove

2019-03-29 06:35 UTC, closed without merging